# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

# Selenium documentation
# https://www.selenium.dev/selenium/docs/api/py/api.html

wd = webdriver.Chrome()
wd.get('https://google.com')
search_box = wd.find_element_by_css_selector(
    'input.gLFyf')  # input box selector
search_box.send_keys('Any query')


def fetch_keywords(query: str):
    # build the google query
    search_url = "https://www.google.com/search?safe=off&site=&tbm=isch&source=hp&q={q}&oq={q}&gs_l=img"

    # load the page
    wd.get(search_url.format(q=query))
    keys = []
    keywords = wd.find_elements_by_css_selector('span.hIOe2')
    for span in keywords:
        # key.add(keywords.get_attribute('aria-label'))
        # print(span.text)
        keys = keys + [span.text]
    return keys

search = input("Search: ")
results = fetch_keywords(search)

# Creates a text file with keywords
for x in results: 
    with open('{}.txt'.format(search), 'a+') as f:
        f.writelines('{}\n'.format(x))

wd.quit()
